# Use an OpenJDK base image
FROM openjdk:11-jdk-slim

# Copy the JAR file into the container
COPY target/java-hello-world.jar /app/java-hello-world.jar

# Set the working directory
WORKDIR /app

# Run the application
CMD ["java", "-jar", "java-hello-world.jar"]
